title: Caio Bianchi
author:
  name: Caio Bianchi
  email: caio@caio.ca

description: >
  Your hub for all things code, creativity, and caffeine! 
  Whether it’s cracking complex algorithms, building sleek web apps, 
  or debugging life’s little bugs, you’ll find it all here.

baseurl: ""
url: "https://caio.ca"

# Build settings
theme: minima
plugins:
  - jekyll-feed

permalink: none

minima:
  skin: solarized
