remote_theme: fongandrew/hydeout

title: Caio Bianchi
author:
  name: Caio Bianchi
  url: caio@caio.ca

description: >
  Software Engineer

baseurl: ""
url: "https://caio.ca"

paginate: 10

permalink: none
sidebar_blog_link: "/"
disqus.shortname: ""
