# Custom theme

title: Caio Bianchi
author:
  name: Caio Bianchi
  url: caio@caio.ca

description: >
  Software Developer

baseurl: ""
url: "https://caio.ca"

paginate: 10

permalink: none

# Build settings
highlighter: rouge
markdown: kramdown

plugins:
  - jekyll-paginate

